import type { NextPage } from "next";
import Head from "next/head";
import { TypedTransComponent } from "~/localization/components/TypedTransComponent";
import { useTypedTranslation } from "~/localization/hooks";
import { initI18n } from "~/localization/services/i18n";
import styles from "~/styles/Home.module.css";

initI18n();

const Home: NextPage = () => {
  const { t } = useTypedTranslation('auth');
  return (
    <div className={styles.container}>
      <Head>
        <title>
          <div>{t("signin.term&policy")}</div>
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.header}>
          {t("signin.hello", { user: "DevGenieur" })}
        </h1>
        <h1 className={styles.title}>
          <TypedTransComponent
            i18nKey="signin.header"
            ns="auth"
            components={{
              Link: <a href="https://github.com/Ar-mane/typed-i18next" />,
            }}
          />
        </h1>

        <div className={styles.grid}>
          <div>{t("signin.hint")}</div>
          <TypedTransComponent
            i18nKey="signin.term&policy"
            ns="auth"
            components={{
              signed: (
                <a
                  style={{ textDecoration: "underline" }}
                  href="https://github.com/Ar-mane/typed-i18next"
                />
              ),
            }}
          />
          <button>{t("signin.signinButton")}</button>
        </div>
      </main>
    </div>
  );
};

export default Home;
